server:
  port: 9527

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka   #单机版
      defaultZone: http://eureka1.com:7001/eureka,http://eureka2.com:7002/eureka
  instance:
    hostname: cloud-gateway-service

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh1           #路由的id,没有固定规则要求唯一，建议配合服务名
          #uri: http://localhost:8001    #匹配后提供服务的路由地址
          uri: lb://CLOUD-PROVIDER-SERVICE    #注意lb
          predicates:
            - Path=/payment/get/**      #断言，路径相匹配的进行路由

      discovery:
        locator:
          enabled: true   #开启cong注册中心动态的创建路由的功能，利用微服务名进行路由


