##这个yml没有配置好

server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xixihac/configcenter.git
          search-paths:
            - configcenter
      label: master
  #rabbitmq的配置
  rabbitmq:
    host: 116.62.212.198
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka1.com:7001/eureka,http://eureka2.com:7002/eureka

#rabbitmq相关配置,暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"   #发post请求http://localhost:3344/actuator/bus-refresh客户端就能全部刷新
                                 #精确打击就是http://localhost:3344/actuator/bus-refresh/config-client:3355
