server:
  port: 80

spring:
  application:
    name: cloud-order-server
  cloud:
    consul:
      host: 116.62.212.198
      port: 8500
      discovery:
        service-name: ${spring.application.name}
