server:
  port: 8006

spring:
  application:
    name: cloud-provider-service
  cloud:
    consul:
      host: 116.62.212.198
      port: 8500
      discovery:
        service-name: ${spring.application.name}
